name: PR Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  preview:
    type: deploy
    params:
      prod: false

  comment:
    needs: [preview]
    type: github-comment
    params:
      payload: "**Preview deployment:** ${{ needs.preview.outputs.deploy_deployment_url }}"
